spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    check-template: true
  datasource:
    url: jdbc:mysql://localhost:3306/trip?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: harbintrip-system
#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.djz.entity
server:
  port: 1314
#百度地图ak
baiduMap:
  ak: h9WIy78OinyTybZbHNwnKbkbobecWh7R
  default:
    city: 哈尔滨



