spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    check-template: true
  datasource:
    url: jdbc:mysql://localhost:3306/djz?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #redis
  redis:
    host: 118.31.34.65
    database: 0
    port: 6379

  application:
    name: harbintrip-system

#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.djz.entity
server:
  port: 1314
  #zookeeper
#dubbo:
#  application:
#    name: provider
#  protocol:
#    name: dubbo
#    port: 20880
#  registry:
#    address: zookeeper://118.31.34.65:2181


